package forexim.assets;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import forexim.util.FEGson.DoNotExpose;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@DynamoDBTable(tableName = "")
@Getter @Setter
public class DBMain {
    @DoNotExpose
    public String updatedBy;
    @DoNotExpose
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public Date createTime;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DoNotExpose
    public Date updateTime;
    @DoNotExpose
    public Long version;
    @DoNotExpose
    public Integer allValues = 1;
}